# Generated by Django 5.1.3 on 2024-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="published_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
