# Generated by Django 5.1.3 on 2024-12-02 10:35

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_newspaper_options_newspaper_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to="images/",
            ),
        ),
    ]
