# Generated by Django 5.1.3 on 2024-12-02 11:33

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to="images/",
            ),
        ),
    ]
