# Generated by Django 5.1.3 on 2024-12-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_redactor_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="is_redactor",
            field=models.BooleanField(default=False),
        ),
    ]
