# Generated by Django 5.1.3 on 2024-12-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_redactor_is_redactor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="redactor",
            old_name="is_redactor",
            new_name="has_access",
        ),
    ]
